# Generated by Django 5.2.10 on 2026-03-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_full_address_and_order_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customeraddress",
            new_name="store_custo_custome_d5f347_idx",
            old_name="store_custo_custome_5fd969_idx",
        ),
    ]
